export default function AgenciesPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        backgroundImage:
          "linear-gradient(rgba(0,0,0,0.55), rgba(0,0,0,0.75)), url('/wpaper2.jpg')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        color: "white",
        fontFamily: "Arial",
      }}
    >
      <section
        style={{
          padding: "90px 20px 70px",
          textAlign: "center",
          maxWidth: "1000px",
          margin: "0 auto",
        }}
      >
        <h1 style={{ fontSize: "52px", marginBottom: "20px" }}>
          Leads for Real Estate Agencies
        </h1>

        <p style={{ fontSize: "22px", lineHeight: "1.5" }}>
          The Kerman Organization generates qualified buyers, sellers and
          investors using AI-powered demand analysis.
        </p>
      </section>

      <section
        style={{
          maxWidth: "1000px",
          margin: "0 auto",
          padding: "0 20px 80px",
        }}
      >
        <h2
          style={{ fontSize: "36px", marginBottom: "20px", textAlign: "center" }}
        >
          How it works
        </h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))",
            gap: "20px",
          }}
        >
          <div style={card}>
            <h3>1. We capture demand</h3>
            <p>
              Our platform attracts buyers, sellers and investors looking for
              property opportunities.
            </p>
          </div>

          <div style={card}>
            <h3>2. AI qualification</h3>
            <p>
              Our AI assistant filters clients by intent, budget, timeline and
              location.
            </p>
          </div>

          <div style={card}>
            <h3>3. You receive qualified leads</h3>
            <p>
              Agencies receive filtered clients ready to discuss real estate
              opportunities.
            </p>
          </div>
        </div>
      </section>

      <section
        style={{
          maxWidth: "1000px",
          margin: "0 auto",
          padding: "0 20px 80px",
        }}
      >
        <h2
          style={{ fontSize: "36px", marginBottom: "20px", textAlign: "center" }}
        >
          Why agencies work with us
        </h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))",
            gap: "20px",
          }}
        >
          <div style={card}>
            <h3>Qualified clients</h3>
            <p>
              No random traffic. Only users actively looking to buy, sell or
              invest.
            </p>
          </div>

          <div style={card}>
            <h3>AI demand filtering</h3>
            <p>Clients are filtered before reaching your agency.</p>
          </div>

          <div style={card}>
            <h3>Private agency dashboard</h3>
            <p>
              Agencies can access a private dashboard to view leads generated by
              our platform.
            </p>
          </div>
        </div>
      </section>

      <section
        style={{
          maxWidth: "800px",
          margin: "0 auto",
          padding: "0 20px 100px",
          textAlign: "center",
        }}
      >
        <h2 style={{ fontSize: "36px", marginBottom: "20px" }}>
          Work with The Kerman Organization
        </h2>

        <p style={{ fontSize: "20px", marginBottom: "30px" }}>
          If you are a real estate agency interested in receiving qualified
          property leads, contact us.
        </p>

        <a
          href="mailto:contact@kermanorganization.com"
          style={{
            padding: "16px 28px",
            background: "white",
            color: "black",
            borderRadius: "10px",
            textDecoration: "none",
            fontWeight: "bold",
          }}
        >
          Contact us
        </a>
      </section>
    </main>
  );
}

const card = {
  backgroundColor: "#111111",
  borderRadius: "14px",
  padding: "28px",
  border: "1px solid #1f1f1f",
};